### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by aleks-spv** [fleetbase/navigator-app#48]
What could be wrong?
`com.facebook.react.common.JavascriptException: Error: ⚠️ Invalid public key given to Fleetbase SDK

This error is located at:
    in App
    in RCTView
    in Unknown
    in RCTView
    in Unknown
    in AppContainer, js engine: hermes, stack:
t@1:931510
useFleetbase@1:885537
use@1:1236281
App@1:614109
renderWithHooks@1:324681
beginWork$1@1:366379
performUnitOfWork@1:352800
workLoopSync@1:352662
renderRootSync@1:352546
performSyncWorkOnRoot@1:349968
flushSyncCallbacks@1:314353
scheduleUpdateOnFiber@1:347109
updateContainer@1:358079
anonymous@1:367407
renderElement@1:82125
renderApplication@1:244251
run@1:237941
runApplication@1:238421
__callFunction@1:73256
anonymous@1:71613
__guard@1:72563
callFunctionReturnFlushedQueue@1:71571

	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:65)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
	at com.facebook.jni.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:77)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
	at java.lang.Thread.run(Thread.java:920)`

**Comment by roncodes** [comment]
Add a public key

**Comment by blessingmwiti** [comment]
I also have this issue, i have the publick key from developers -> api -> public key, which starts with flb_live but it is not working, I get  ERROR  Warning: Error: ⚠️ Invalid public key given to Fleetbase SDK
I have everything else sorted out

**Comment by roncodes** [comment]
Does it point to your own instance? If so make sure it's configured for that too.

**Comment by blessingmwiti** [comment]
> Does it point to your own instance? If so make sure it's configured for that too.

Yes, it does point to my instance, using the api just like in the env example
