### ISSUE TITLE
Unable to build Android app

### ISSUE THREAD

**Issue by Qoyyuum** [fleetbase/navigator-app#5]
This happened after I ran `./gradlew buildRelease` in `android` folder.

```shell
> Configure project :react-native-reanimated
No AAR for react-native-reanimated found. Attempting to build from source.
Android gradle plugin: 4.2.2
Gradle: 6.9

> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
                    Welcome to Metro!
              Fast - Scalable - Integrated


Failed to construct transformer:  Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:138:10)
    at stableHash (F:\sides\navigator-app\node_modules\metro-cache\src\stableHash.js:19:8)
    at Object.getCacheKey (F:\sides\navigator-app\node_modules\metro-transform-worker\src\index.js:593:7)
    at getTransformCacheKey (F:\sides\navigator-app\node_modules\metro\src\DeltaBundler\getTransformCacheKey.js:24:19)
    at new Transformer (F:\sides\navigator-app\node_modules\metro\src\DeltaBundler\Transformer.js:48:9)
    at F:\sides\navigator-app\node_modules\metro\src\Bundler.js:22:29
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processTimers (node:internal/timers:511:9) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
error Cannot read properties of undefined (reading 'transformFile').
TypeError: Cannot read properties of undefined (reading 'transformFile')
    at Bundler.transformFile (F:\sides\navigator-app\node_modules\metro\src\Bundler.js:48:30)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processTimers (node:internal/timers:511:9)
    at async Object.transform (F:\sides\navigator-app\node_modules\metro\src\lib\transformHelpers.js:101:12)
    at async processModule (F:\sides\navigator-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:137:18)
    at async traverseDependenciesForSingleFile (F:\sides\navigator-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:131:3)
    at async Promise.all (index 0)
    at async initialTraverseDependencies (F:\sides\navigator-app\node_modules\metro\src\DeltaBundler\traverseDependencies.js:114:3)
    at async DeltaCalculator._getChangedDependencies (F:\sides\navigator-app\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:164:25)
    at async DeltaCalculator.getDelta (F:\sides\navigator-app\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:94:16)
info Run CLI with --verbose flag for more details.

> Task :app:bundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

Need help please.

**Comment by manishsainju** [comment]
Try using node version 14 or 16 @Qoyyuum

**Comment by roncodes** [comment]
Fixed in latest https://github.com/fleetbase/navigator-app/pull/54
